//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreRestBL.StoreDASoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/StoreSoap.Data.Models")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="order", Namespace="http://schemas.datacontract.org/2004/07/StoreSoap.Data.Models")]
    [System.SerializableAttribute()]
    public partial class order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StoreRestBL.StoreDASoap.product[] productsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal totalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StoreRestBL.StoreDASoap.product[] products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                if ((this.totalPriceField.Equals(value) != true)) {
                    this.totalPriceField = value;
                    this.RaisePropertyChanged("totalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreDASoap.IStoreDataSoap")]
    public interface IStoreDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/GetProducts", ReplyAction="http://tempuri.org/IStoreDataSoap/GetProductsResponse")]
        StoreRestBL.StoreDASoap.product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/GetProducts", ReplyAction="http://tempuri.org/IStoreDataSoap/GetProductsResponse")]
        System.Threading.Tasks.Task<StoreRestBL.StoreDASoap.product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/AddProduct", ReplyAction="http://tempuri.org/IStoreDataSoap/AddProductResponse")]
        bool AddProduct(StoreRestBL.StoreDASoap.product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/AddProduct", ReplyAction="http://tempuri.org/IStoreDataSoap/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(StoreRestBL.StoreDASoap.product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/DeleteProduct", ReplyAction="http://tempuri.org/IStoreDataSoap/DeleteProductResponse")]
        bool DeleteProduct(StoreRestBL.StoreDASoap.product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/DeleteProduct", ReplyAction="http://tempuri.org/IStoreDataSoap/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(StoreRestBL.StoreDASoap.product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/GetOders", ReplyAction="http://tempuri.org/IStoreDataSoap/GetOdersResponse")]
        StoreRestBL.StoreDASoap.order[] GetOders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/GetOders", ReplyAction="http://tempuri.org/IStoreDataSoap/GetOdersResponse")]
        System.Threading.Tasks.Task<StoreRestBL.StoreDASoap.order[]> GetOdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/AddOrder", ReplyAction="http://tempuri.org/IStoreDataSoap/AddOrderResponse")]
        bool AddOrder(StoreRestBL.StoreDASoap.order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/AddOrder", ReplyAction="http://tempuri.org/IStoreDataSoap/AddOrderResponse")]
        System.Threading.Tasks.Task<bool> AddOrderAsync(StoreRestBL.StoreDASoap.order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/DeleteOrder", ReplyAction="http://tempuri.org/IStoreDataSoap/DeleteOrderResponse")]
        bool DeleteOrder(StoreRestBL.StoreDASoap.order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreDataSoap/DeleteOrder", ReplyAction="http://tempuri.org/IStoreDataSoap/DeleteOrderResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderAsync(StoreRestBL.StoreDASoap.order o);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreDataSoapChannel : StoreRestBL.StoreDASoap.IStoreDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreDataSoapClient : System.ServiceModel.ClientBase<StoreRestBL.StoreDASoap.IStoreDataSoap>, StoreRestBL.StoreDASoap.IStoreDataSoap {
        
        public StoreDataSoapClient() {
        }
        
        public StoreDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreRestBL.StoreDASoap.product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<StoreRestBL.StoreDASoap.product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool AddProduct(StoreRestBL.StoreDASoap.product p) {
            return base.Channel.AddProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(StoreRestBL.StoreDASoap.product p) {
            return base.Channel.AddProductAsync(p);
        }
        
        public bool DeleteProduct(StoreRestBL.StoreDASoap.product p) {
            return base.Channel.DeleteProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(StoreRestBL.StoreDASoap.product p) {
            return base.Channel.DeleteProductAsync(p);
        }
        
        public StoreRestBL.StoreDASoap.order[] GetOders() {
            return base.Channel.GetOders();
        }
        
        public System.Threading.Tasks.Task<StoreRestBL.StoreDASoap.order[]> GetOdersAsync() {
            return base.Channel.GetOdersAsync();
        }
        
        public bool AddOrder(StoreRestBL.StoreDASoap.order o) {
            return base.Channel.AddOrder(o);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderAsync(StoreRestBL.StoreDASoap.order o) {
            return base.Channel.AddOrderAsync(o);
        }
        
        public bool DeleteOrder(StoreRestBL.StoreDASoap.order o) {
            return base.Channel.DeleteOrder(o);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderAsync(StoreRestBL.StoreDASoap.order o) {
            return base.Channel.DeleteOrderAsync(o);
        }
    }
}
